-- MySQL Script generated by MySQL Workbench
-- Sat Mar 25 14:39:53 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projectCaraguatay
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `projectCaraguatay` ;

-- -----------------------------------------------------
-- Schema projectCaraguatay
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projectCaraguatay` DEFAULT CHARACTER SET utf8 ;
USE `projectCaraguatay` ;

-- -----------------------------------------------------
-- Table `projectCaraguatay`.`DigitalPoint`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectCaraguatay`.`DigitalPoint` ;

CREATE TABLE IF NOT EXISTS `projectCaraguatay`.`DigitalPoint` (
  `idDigitalPoint` VARCHAR(36) NOT NULL,
  `title` VARCHAR(16) NOT NULL,
  `description` VARCHAR(32) NOT NULL,
  `beginDate` DATE NOT NULL,
  `status` TINYINT NOT NULL,
  `requirements` VARCHAR(128) NULL,
  `Users_idusers` VARCHAR(40) NOT NULL,
  `idDpCategory` INT NOT NULL,
  `idmedia` INT NOT NULL,
  PRIMARY KEY (`idDigitalPoint`, `title`, `idusers`, `idDpCategory`, `idmedia`),
  UNIQUE INDEX `idAds_UNIQUE` (`idDigitalPoint` ASC) VISIBLE,
  INDEX `fk_DigitalPoint_Users1_idx` (`idusers` ASC) VISIBLE,
  INDEX `fk_DigitalPoint_Dp_Category1_idx` (`idDpCategory` ASC) VISIBLE,
  INDEX `fk_DigitalPoint_Media1_idx` (`idmedia1` ASC) VISIBLE,
  CONSTRAINT `fk_DigitalPoint_Users1`
    FOREIGN KEY (`idusers`)
    REFERENCES `projectCaraguatay`.`Users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DigitalPoint_Dp_Category1`
    FOREIGN KEY (`idDpCategory`)
    REFERENCES `projectCaraguatay`.`Dp_Category` (`idDpCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DigitalPoint_Media1`
    FOREIGN KEY (`Media_idmedia1`)
    REFERENCES `projectCaraguatay`.`Media` (`idmedia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectCaraguatay`.`Dp_Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectCaraguatay`.`Dp_Category` ;

CREATE TABLE IF NOT EXISTS `projectCaraguatay`.`Dp_Category` (
  `idDpCategory` INT NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`idDpCategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectCaraguatay`.`Media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectCaraguatay`.`Media` ;

CREATE TABLE IF NOT EXISTS `projectCaraguatay`.`Media` (
  `idmedia` INT NOT NULL,
  `mediaType` VARCHAR(5) NULL,
  `path` VARCHAR(256) NULL,
  `idPost` INT NOT NULL,
  PRIMARY KEY (`idmedia`, `idPost`),
  UNIQUE INDEX `idmedia_UNIQUE` (`idmedia` ASC) VISIBLE,
  INDEX `fk_Media_Posts1_idx` (`idPost` ASC) VISIBLE,
  CONSTRAINT `fk_Media_Posts1`
    FOREIGN KEY (`idPost`)
    REFERENCES `projectCaraguatay`.`Posts` (`idPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectCaraguatay`.`Posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectCaraguatay`.`Posts` ;

CREATE TABLE IF NOT EXISTS `projectCaraguatay`.`Posts` (
  `idPost` INT NOT NULL,
  `title` VARCHAR(32) NOT NULL,
  `body` VARCHAR(256) NOT NULL,
  `creationDate` DATETIME NOT NULL,
  `idusers` VARCHAR(40) NOT NULL,
  `idPostCategory` INT NOT NULL,
  PRIMARY KEY (`idPost`, `idusers`, `idPostCategory`),
  INDEX `fk_Posts_Users1_idx` (`idusers` ASC) VISIBLE,
  INDEX `fk_Posts_postCategory1_idx` (`idPostCategory` ASC) VISIBLE,
  CONSTRAINT `fk_Posts_Users1`
    FOREIGN KEY (`idusers`)
    REFERENCES `projectCaraguatay`.`Users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Posts_postCategory1`
    FOREIGN KEY (`postCategory_idPostCategory`)
    REFERENCES `projectCaraguatay`.`postCategory` (`idPostCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectCaraguatay`.`UserRole`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectCaraguatay`.`UserRole` ;

CREATE TABLE IF NOT EXISTS `projectCaraguatay`.`UserRole` (
  `idRole` INT NOT NULL,
  `descType` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idRole`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectCaraguatay`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectCaraguatay`.`Users` ;

CREATE TABLE IF NOT EXISTS `projectCaraguatay`.`Users` (
  `idusers` VARCHAR(40) NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `lastName` VARCHAR(20) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `creationDate` DATETIME NOT NULL,
  `enabled` VARCHAR(36) BINARY NOT NULL,
  `avatar` VARCHAR(256) NOT NULL,
  `idRole` INT NOT NULL,
  PRIMARY KEY (`idusers`, `idRole`),
  UNIQUE INDEX `idusers_UNIQUE` (`idusers` ASC) VISIBLE,
  INDEX `fk_Users_UserRole1_idx` (`idRole` ASC) VISIBLE,
  CONSTRAINT `fk_Users_UserRole1`
    FOREIGN KEY (`idRole`)
    REFERENCES `projectCaraguatay`.`UserRole` (`idRole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectCaraguatay`.`postCategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectCaraguatay`.`postCategory` ;

CREATE TABLE IF NOT EXISTS `projectCaraguatay`.`postCategory` (
  `idPostCategory` INT NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`idPostCategory`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
